#!/usr/bin/env python3
"""
Convert Strix (AI pentest agent) SARIF output into findings for the report pipeline.

Strix runs in source mode (no live target) as a weekly deep scan. It emits
findings.sarif with CVSS (security-severity), CWE tags, a rich description, and a
remediation (fixes[].description). We map those into the from_custom schema and
APPEND to OUT (custom.json), preserving Strix's own why/fix/CVSS/CWE (they are
authoritative for these findings - not re-generated by the curated map).

Env:
  SARIF        default strix_runs/*/findings.sarif (first match) or set explicitly
  OUT          default custom.json
  STRIX_PREFIX repo-root path of the scan target, prepended to SARIF uris
               (default local-setup)  e.g. local-setup or local-setup/ansible
"""
import os, re, json, glob
from scope import in_scope   # shared Ansible-deployment scope (see .github/SECURITY-SCOPE.md)

OUT = os.environ.get("OUT", "custom.json")
PREFIX = os.environ.get("STRIX_PREFIX", "local-setup").strip("/")
BASE = os.environ.get("BASE", ".")   # repo root, to VALIDATE that reported paths are real
SARIF = os.environ.get("SARIF", "")
if not SARIF:
    cands = sorted(glob.glob("strix_runs/*/findings.sarif"), key=os.path.getmtime, reverse=True)
    SARIF = cands[0] if cands else "findings.sarif"

_PATH_RE = re.compile(r"[\w][\w./-]+\.(?:json|ya?ml|md|sh|j2|py|js|ts|lock|env|toml|xml|properties|sql|conf|cfg|ini)")


def sev_from_cvss(c):
    try: c = float(c)
    except Exception: return "MEDIUM"
    return "CRITICAL" if c >= 9 else "HIGH" if c >= 7 else "MEDIUM" if c >= 4 else "LOW"


def rel(uri):
    uri = (uri or "").replace("file://", "").lstrip("./").lstrip("/")
    if uri and PREFIX and not uri.startswith(PREFIX + "/") and not uri.startswith("local-setup/"):
        uri = f"{PREFIX}/{uri}"
    return uri


def cwe_of(rule_id, tags):
    for t in [rule_id] + list(tags or []):
        m = re.search(r"CWE-(\d+)", str(t or ""), re.I)
        if m:
            return "CWE-" + m.group(1)
    return ""


def area_of(uri):
    u = (uri or "").lower()
    if "docker-compose" in u or u.endswith((".yml", ".yaml")) and "compose" in u:
        return "docker-compose"
    return "ansible"


def clean(text, title):
    """Drop a leading duplicate title line from the description body."""
    t = (text or "").strip()
    if title and t.lower().startswith(title.lower()):
        t = t[len(title):].lstrip("\n :-").strip()
    return " ".join(t.split())  # collapse whitespace/newlines for a compact cell


def _exists(relpath):
    return bool(relpath) and os.path.exists(os.path.join(BASE, relpath))


def resolve_location(raw_uri, title, why):
    """Deliberative location check. Strix's reported uri is often wrong/hallucinated
    (e.g. `SECURITY.md` for a handlebars CVE that's really in tests/package-lock.json).
    1) if the reported path exists in the repo, trust it;
    2) else recover a real path mentioned in the title/description;
    3) else give up (None) so the caller drops the finding - we never emit a broken link.
    Returns (repo_relative_path | None, recovered: bool)."""
    p = rel(raw_uri)
    if _exists(p):
        return p, False
    for tok in _PATH_RE.findall(f"{title}\n{why}"):
        cand = rel(tok)
        if _exists(cand):
            return cand, True
    return None, True


def fix_title_path(title, resolved):
    """If the title names a `path` that differs from the validated location, replace it
    with the real file so the title never claims the wrong file (Strix reused one title
    for several distinct files)."""
    target = resolved[len(PREFIX) + 1:] if resolved.startswith(PREFIX + "/") else resolved
    toks = re.findall(r"`([^`]+)`", title)
    pathish = [t for t in toks if "/" in t or _PATH_RE.fullmatch(t)]
    if pathish and target not in pathish and os.path.basename(target) not in [os.path.basename(t) for t in pathish]:
        return title.replace(f"`{pathish[-1]}`", f"`{target}`")
    return title


def main():
    try:
        sar = json.load(open(SARIF))
    except Exception as e:
        print(f"no/invalid Strix sarif ({e}); skipping Strix findings.")
        return
    run = (sar.get("runs") or [{}])[0]
    rules = run.get("tool", {}).get("driver", {}).get("rules", [])
    out = []
    dropped = []
    out_of_scope = []
    for r in run.get("results", []):
        rid = r.get("ruleId") or ""
        rule = {}
        if isinstance(r.get("ruleIndex"), int) and 0 <= r["ruleIndex"] < len(rules):
            rule = rules[r["ruleIndex"]]
        elif rid:
            rule = next((x for x in rules if x.get("id") == rid), {})
        rp = rule.get("properties", {}) or {}
        props = r.get("properties", {}) or {}
        cvss = props.get("security-severity") or rp.get("security-severity")
        title = (rule.get("name") or (r.get("message", {}) or {}).get("text", "").split("\n")[0]).strip()[:140]
        loc = ((r.get("locations") or [{}])[0].get("physicalLocation") or {})
        raw_uri = (loc.get("artifactLocation") or {}).get("uri")
        line = (loc.get("region") or {}).get("startLine")
        why = clean((r.get("message", {}) or {}).get("text", ""), title)
        fixes = r.get("fixes") or []
        fix = clean((fixes[0].get("description", {}) or {}).get("text", ""), "") if fixes else ""
        cwe = cwe_of(rid, rp.get("tags"))
        guide = f"https://cwe.mitre.org/data/definitions/{cwe.split('-')[1]}.html" if cwe else ""

        # DELIBERATIVE location validation - never emit a finding we cannot pin to a real file.
        resolved, recovered = resolve_location(raw_uri, title, why)
        if not resolved:
            dropped.append(f"{rid} (uri={raw_uri!r} - no real repo file found)")
            continue
        # SCOPE gate - drop findings outside the Ansible remote-server deployment set.
        if not in_scope(resolved):
            out_of_scope.append(f"{rid} ({resolved})")
            continue
        if recovered:
            line = None                       # Strix's line was for its wrong uri; don't trust it
        title = fix_title_path(title, resolved)   # always: the title must name the validated file

        out.append({"source": "Strix", "area": area_of(resolved), "severity": sev_from_cvss(cvss),
                    "id": rid or "STRIX", "title": title[:140], "file": resolved, "line": line,
                    "desc": "", "guide": guide,
                    "why": why, "fix": fix or "See the Strix-generated patch for the concrete change.",
                    "cvss": round(float(cvss), 1) if cvss else None, "cwe": cwe})

    existing = []
    if os.path.exists(OUT):
        try: existing = json.load(open(OUT))
        except Exception: existing = []
    json.dump(existing + out, open(OUT, "w"), indent=1)
    msg = f"Strix: added {len(out)} finding(s) from {SARIF} -> {OUT} (total {len(existing) + len(out)})."
    if dropped:
        msg += f" Dropped {len(dropped)} with unverifiable location: " + "; ".join(dropped) + "."
    if out_of_scope:
        msg += (f" Dropped {len(out_of_scope)} outside the Ansible deployment scope "
                f"(see .github/SECURITY-SCOPE.md): " + "; ".join(out_of_scope) + ".")
    print(msg)


if __name__ == "__main__":
    main()
