#!/usr/bin/env python3
"""
Convert Strix (AI pentest agent) SARIF output into findings for the report pipeline.

Strix runs in source mode (no live target) as a weekly deep scan. It emits
findings.sarif with CVSS (security-severity), CWE tags, a rich description, and a
remediation (fixes[].description). We map those into the from_custom schema and
APPEND to OUT (custom.json), preserving Strix's own why/fix/CVSS/CWE (they are
authoritative for these findings - not re-generated by the curated map).

Env:
  SARIF        default strix_runs/*/findings.sarif (first match) or set explicitly
  OUT          default custom.json
  STRIX_PREFIX repo-root path of the scan target, prepended to SARIF uris
               (default local-setup)  e.g. local-setup or local-setup/ansible
"""
import os, re, json, glob

OUT = os.environ.get("OUT", "custom.json")
PREFIX = os.environ.get("STRIX_PREFIX", "local-setup").strip("/")
SARIF = os.environ.get("SARIF", "")
if not SARIF:
    cands = sorted(glob.glob("strix_runs/*/findings.sarif"), key=os.path.getmtime, reverse=True)
    SARIF = cands[0] if cands else "findings.sarif"


def sev_from_cvss(c):
    try: c = float(c)
    except Exception: return "MEDIUM"
    return "CRITICAL" if c >= 9 else "HIGH" if c >= 7 else "MEDIUM" if c >= 4 else "LOW"


def rel(uri):
    uri = (uri or "").replace("file://", "").lstrip("./").lstrip("/")
    if uri and PREFIX and not uri.startswith(PREFIX + "/") and not uri.startswith("local-setup/"):
        uri = f"{PREFIX}/{uri}"
    return uri


def cwe_of(rule_id, tags):
    for t in [rule_id] + list(tags or []):
        m = re.search(r"CWE-(\d+)", str(t or ""), re.I)
        if m:
            return "CWE-" + m.group(1)
    return ""


def area_of(uri):
    u = (uri or "").lower()
    if "docker-compose" in u or u.endswith((".yml", ".yaml")) and "compose" in u:
        return "docker-compose"
    return "ansible"


def clean(text, title):
    """Drop a leading duplicate title line from the description body."""
    t = (text or "").strip()
    if title and t.lower().startswith(title.lower()):
        t = t[len(title):].lstrip("\n :-").strip()
    return " ".join(t.split())  # collapse whitespace/newlines for a compact cell


def main():
    try:
        sar = json.load(open(SARIF))
    except Exception as e:
        print(f"no/invalid Strix sarif ({e}); skipping Strix findings.")
        return
    run = (sar.get("runs") or [{}])[0]
    rules = run.get("tool", {}).get("driver", {}).get("rules", [])
    out = []
    for r in run.get("results", []):
        rid = r.get("ruleId") or ""
        rule = {}
        if isinstance(r.get("ruleIndex"), int) and 0 <= r["ruleIndex"] < len(rules):
            rule = rules[r["ruleIndex"]]
        elif rid:
            rule = next((x for x in rules if x.get("id") == rid), {})
        rp = rule.get("properties", {}) or {}
        props = r.get("properties", {}) or {}
        cvss = props.get("security-severity") or rp.get("security-severity")
        title = rule.get("name") or (r.get("message", {}) or {}).get("text", "").split("\n")[0]
        title = title.strip()[:120]
        loc = ((r.get("locations") or [{}])[0].get("physicalLocation") or {})
        uri = rel((loc.get("artifactLocation") or {}).get("uri"))
        line = (loc.get("region") or {}).get("startLine")
        why = clean((r.get("message", {}) or {}).get("text", ""), title)
        fixes = r.get("fixes") or []
        fix = clean((fixes[0].get("description", {}) or {}).get("text", ""), "") if fixes else ""
        cwe = cwe_of(rid, rp.get("tags"))
        guide = f"https://cwe.mitre.org/data/definitions/{cwe.split('-')[1]}.html" if cwe else ""
        if not uri:
            continue
        out.append({"source": "Strix", "area": area_of(uri), "severity": sev_from_cvss(cvss),
                    "id": rid or "STRIX", "title": title, "file": uri, "line": line,
                    "desc": "", "guide": guide,
                    "why": why, "fix": fix or "See the Strix-generated patch for the concrete change.",
                    "cvss": round(float(cvss), 1) if cvss else None, "cwe": cwe})

    existing = []
    if os.path.exists(OUT):
        try: existing = json.load(open(OUT))
        except Exception: existing = []
    json.dump(existing + out, open(OUT, "w"), indent=1)
    print(f"Strix: added {len(out)} finding(s) from {SARIF} -> {OUT} (total {len(existing) + len(out)}).")


if __name__ == "__main__":
    main()
